In [1]:
# set up
import pandas as pd
import numpy as np
import pickle
import time 
import os
from datetime import datetime
from operator import itemgetter
data_folder_path = 'C:\\Users\\goodluck\\Desktop\\DB'
raw_data_path =  "C:\\Users\\goodluck\\Desktop\\DB\\raw_data"
storage_path =  "C:\\Users\\goodluck\\Desktop\\DB\\database_storage"
auto_path =  "C:\\Users\\goodluck\\Desktop\\DB\\auto_update"
DTBS_path = os.path.join(storage_path, "DTBS.pkl")
with open(DTBS_path, 'rb') as f:  
    DTBS = pickle.load(f)

In [2]:
cz_path =  os.path.join(auto_path, "cz06-27-07-03.csv")
cz_df = pd.read_csv(cz_path, index_col = 0)
cz_df

,110088.SH,113545.SH,113631.SH,123128.SZ,123156.SZ,127027.SZ,127061.SZ,110047.SH,110063.SH,110070.SH,...,113003.SH,128003.SZ,128001.SZ,110007.SH,110016.SH,125887.SZ,110003.SH,129031.SZ,125731.SZ,110009.SH
2023-06-27,94.7434,105.5451,99.4083,98.5499,80.9883,102.9418,92.9902,110.7761,106.7118,105.5316,...,0,0,0,0,0,0,0,0,0,0
2023-06-28,94.6885,105.5121,99.4306,98.5608,80.9293,102.9707,92.9350,110.7871,106.6905,105.5389,...,0,0,0,0,0,0,0,0,0,0
2023-06-29,94.7668,105.5198,99.5031,98.5809,80.9838,102.9514,92.9970,110.7887,106.7027,105.5632,...,0,0,0,0,0,0,0,0,0,0
2023-06-30,94.9067,105.5602,99.5244,98.6064,81.0895,103.0504,93.0764,110.8427,106.7811,105.6422,...,0,0,0,0,0,0,0,0,0,0
2023-07-03,94.9652,105.6452,99.5821,98.6570,81.2078,103.1587,93.1786,110.8799,106.8638,105.7066,...,0,0,0,0,0,0,0,0,0,0

In [3]:
count = 0
for code in DTBS['A'].keys():
    count += 1
    for date in DTBS['D']['day']:
        if DTBS['A'][code][date]['ia'] == 1:
            DTBS['A'][code][date]['csv'] = ((100.0 / DTBS['A'][code][date]['csp']) *   DTBS['E'][DTBS['B'][code]['sc']][date]['cl'])
            
        else:
            DTBS['A'][code][date]['csv'] = 0
    print(count)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787

In [4]:
dts = DTBS['D']['day'][1573:1578]
dts[-1]
# must be before 2023/4/28
dts

['2023-06-27', '2023-06-28', '2023-06-29', '2023-06-30', '2023-07-03']

In [5]:
cz_df
#5/4 - 5/18

,110088.SH,113545.SH,113631.SH,123128.SZ,123156.SZ,127027.SZ,127061.SZ,110047.SH,110063.SH,110070.SH,...,113003.SH,128003.SZ,128001.SZ,110007.SH,110016.SH,125887.SZ,110003.SH,129031.SZ,125731.SZ,110009.SH
2023-06-27,94.7434,105.5451,99.4083,98.5499,80.9883,102.9418,92.9902,110.7761,106.7118,105.5316,...,0,0,0,0,0,0,0,0,0,0
2023-06-28,94.6885,105.5121,99.4306,98.5608,80.9293,102.9707,92.9350,110.7871,106.6905,105.5389,...,0,0,0,0,0,0,0,0,0,0
2023-06-29,94.7668,105.5198,99.5031,98.5809,80.9838,102.9514,92.9970,110.7887,106.7027,105.5632,...,0,0,0,0,0,0,0,0,0,0
2023-06-30,94.9067,105.5602,99.5244,98.6064,81.0895,103.0504,93.0764,110.8427,106.7811,105.6422,...,0,0,0,0,0,0,0,0,0,0
2023-07-03,94.9652,105.6452,99.5821,98.6570,81.2078,103.1587,93.1786,110.8799,106.8638,105.7066,...,0,0,0,0,0,0,0,0,0,0

In [6]:
for code in cz_df.columns:
    count = 0
    for date in dts:
        if DTBS['A'][code][date]['ia'] == 1:
            DTBS['A'][code][date]['cz'] = cz_df.iloc[count][code]
            
        else:
            DTBS['A'][code][date]['cz'] = 0
        count += 1

In [7]:
for code in cz_df.columns:
    for date in dts:
        if DTBS['A'][code][date]['ia'] == 1:
            if code == '110057.SH' or code == '113016.SH':
                DTBS['A'][code][date]['pd'] = 0
                
                # 这里是一个坑，在cz wind api里面应该每天一行一行的添加，而不是按五天标准，不然强赎会有问题
            else:
#                 print(code)
                DTBS['A'][code][date]['pd'] = ((DTBS['A'][code][date]['csv'] /  DTBS['A'][code][date]['cz'] ) - 1.0) * 100
            
        else:
            DTBS['A'][code][date]['pd'] = 0

C:\Users\goodluck\AppData\Local\Temp\ipykernel_1580\3243641729.py:10: RuntimeWarning: divide by zero encountered in double_scalars
  DTBS['A'][code][date]['pd'] = ((DTBS['A'][code][date]['csv'] /  DTBS['A'][code][date]['cz'] ) - 1.0) * 100

In [9]:
DTBS['A']['110088.SH']['2023-06-27']

{'cpr': 44.16,
 'dp': 114.961,
 'dl': 159.12099999999998,
 'ytm': -0.68,
 'bl': 30.0,
 'trt': 0.87,
 'yl': 5.222,
 'csp': 14.12,
 'ia': 1,
 'xx': 0,
 'hs': 0,
 'csv': 79.74504249291785,
 'qs': 0,
 'qs15': 0,
 'qs30': 0,
 'cz': 94.7434,
 'pd': -15.83050376815921}

In [8]:
# save
f_save = open(DTBS_path, 'wb')
pickle.dump(DTBS, f_save)
f_save.close()